title: A Fairly Odd Science Confabulation
description: If only wishes came true

remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
